import { 
  Student, 
  Section, 
  Teacher, 
  Invoice, 
  AttendanceRecord, 
  GradeEntry, 
  DisciplinaryAction, 
  RecommendationRequest, 
  SchoolNotice, 
  TeacherDayOffRequest,
  BankStatementRow,
  StudentEvaluation,
  InstitutionalUser
} from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'OSK-2026-0901',
    accountNumber: 'ACC-90412',
    fullName: 'Yared Melaku Tadesse',
    gender: 'Male',
    dob: '2011-04-12',
    grade: 9,
    stream: null,
    sectionId: '9A',
    eighthGradeCertAttached: true,
    entranceExamScore: 88,
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'Preparatory Junior School',
      isSameSchool: true,
    },
    parents: {
      fatherName: 'Melaku Tadesse Gebre',
      fatherPhone: '+251 91 123 4567',
      motherName: 'Aster Wolde Mikael',
      motherPhone: '+251 92 345 6789',
      email: 'nexgriddigital@gmail.com',
    },
    emergencyContact: {
      name: 'Dr. Girma Tadesse (Uncle)',
      phone1: '+251 91 888 1234',
      phone2: '+251 94 555 9876',
      relationship: 'Uncle',
    },
    registrationStatus: 'COMPLETE',
    temporaryPassword: 'TempPassword#2026',
    mustChangePasswordOnLogin: false,
    password: 'Password@123',
    idCardCollected: true,
    streamChangeRequest: null,
    lostIdRequest: null,
  },
  {
    id: 'OSK-2026-0902',
    accountNumber: 'ACC-90415',
    fullName: 'Sara Hailemariam Mengistu',
    gender: 'Female',
    dob: '2011-08-25',
    grade: 9,
    stream: null,
    sectionId: '9B',
    eighthGradeCertAttached: true,
    entranceExamScore: 94,
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'Bethlehem Academy',
      isSameSchool: false,
    },
    parents: {
      fatherName: 'Hailemariam Mengistu',
      fatherPhone: '+251 91 222 3344',
      motherName: 'Tigist Bekele',
      motherPhone: '+251 93 444 5566',
      email: 'hailemariam.mengistu@gmail.com',
    },
    emergencyContact: {
      name: 'Ato Solomon Mengistu',
      phone1: '+251 91 777 6655',
      phone2: '+251 92 111 2233',
      relationship: 'Elder Brother',
    },
    registrationStatus: 'COMPLETE',
    temporaryPassword: 'SaraPassword!9',
    mustChangePasswordOnLogin: false,
    password: 'Password@123',
    idCardCollected: true,
    streamChangeRequest: null,
    lostIdRequest: null,
  },
  {
    id: 'OSK-2026-1001',
    accountNumber: 'ACC-10283',
    fullName: 'Natnael Yohannes Kebede',
    gender: 'Male',
    dob: '2010-02-14',
    grade: 10,
    stream: null,
    sectionId: '10A',
    eighthGradeCertAttached: true,
    entranceExamScore: null,
    ninthGradeResults: { math: 89, english: 84, science: 91, average: 88.0 },
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'Model High School',
      isSameSchool: true,
    },
    parents: {
      fatherName: 'Yohannes Kebede',
      fatherPhone: '+251 91 555 4321',
      motherName: 'Rahel Assefa',
      motherPhone: '+251 92 666 5432',
      email: 'yohannes.kebede@gmail.com',
    },
    emergencyContact: {
      name: 'Woizero Hiwot Kebede',
      phone1: '+251 91 333 9988',
      phone2: '+251 94 222 1100',
      relationship: 'Aunt',
    },
    registrationStatus: 'COMPLETE',
    mustChangePasswordOnLogin: false,
    password: 'Password@123',
    idCardCollected: true,
    streamChangeRequest: null,
    lostIdRequest: {
      id: 'LID-8821',
      date: '2026-09-12',
      reason: 'Lost wallet on transit',
      financeCleared: true,
      libraryCleared: true,
      homeroomTeacherCleared: true,
      principalCleared: false,
      principalOverride: false,
      replacementFeePaid: false,
      status: 'PENDING_CLEARANCES',
    },
  },
  {
    id: 'OSK-2026-1101',
    accountNumber: 'ACC-11904',
    fullName: 'Blen Daniel Alemu',
    gender: 'Female',
    dob: '2009-11-03',
    grade: 11,
    stream: 'Social Sciences',
    // NOTICE: Has an active pending stream change request!
    // Per requirement: "if the request is neither Accepted nor denied the system shouldn't assign the student a classroom and don't put them in the attendance."
    sectionId: null,
    eighthGradeCertAttached: true,
    entranceExamScore: 92,
    ninthGradeResults: { math: 82, english: 94, science: 80, average: 85.3 },
    tenthGradeResults: { math: 85, english: 96, science: 81, average: 87.3 },
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'Model High School',
      isSameSchool: true,
    },
    parents: {
      fatherName: 'Daniel Alemu Zewde',
      fatherPhone: '+251 91 444 8899',
      motherName: 'Bethlehem Demisse',
      motherPhone: '+251 92 888 7766',
    },
    emergencyContact: {
      name: 'Fikadu Alemu',
      phone1: '+251 91 100 2299',
      phone2: '+251 93 400 5588',
      relationship: 'Grandfather',
    },
    registrationStatus: 'COMPLETE',
    mustChangePasswordOnLogin: false,
    password: 'Password@123',
    idCardCollected: true,
    streamChangeRequest: {
      id: 'SCR-3019',
      requestedStream: 'Natural Sciences',
      requestDate: '2026-09-08',
      daysSinceSchoolStart: 8, // within 15 days
      reason: 'Wish to pursue Biomedical Engineering in university after re-evaluating career goals.',
      status: 'PENDING',
    },
    lostIdRequest: null,
  },
  {
    id: 'OSK-2026-1102',
    accountNumber: 'ACC-11908',
    fullName: 'Eyob Kassahun Tefera',
    gender: 'Male',
    dob: '2009-06-19',
    grade: 11,
    stream: 'Natural Sciences',
    sectionId: '11-NAT-A',
    eighthGradeCertAttached: true,
    entranceExamScore: 89,
    ninthGradeResults: { math: 95, english: 87, science: 94, average: 92.0 },
    tenthGradeResults: { math: 98, english: 89, science: 96, average: 94.3 },
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'Model High School',
      isSameSchool: true,
    },
    parents: {
      fatherName: 'Kassahun Tefera',
      fatherPhone: '+251 91 666 7788',
      motherName: 'Senait Desta',
      motherPhone: '+251 92 777 8899',
    },
    emergencyContact: {
      name: 'Ato Getachew Tefera',
      phone1: '+251 91 999 3322',
      phone2: '+251 94 444 8811',
      relationship: 'Uncle',
    },
    registrationStatus: 'COMPLETE',
    mustChangePasswordOnLogin: false,
    password: 'Password@123',
    idCardCollected: true,
    streamChangeRequest: null,
    lostIdRequest: null,
  },
  {
    id: 'OSK-2026-1201',
    accountNumber: 'ACC-12480',
    fullName: 'Hanna Samuel Worku',
    gender: 'Female',
    dob: '2008-09-10',
    grade: 12,
    stream: 'Natural Sciences',
    sectionId: '12-NAT-A',
    eighthGradeCertAttached: true,
    entranceExamScore: 96,
    ninthGradeResults: { math: 92, english: 90, science: 95, average: 92.3 },
    tenthGradeResults: { math: 94, english: 93, science: 96, average: 94.3 },
    eleventhGradeResults: { math: 96, physics_history: 95, chemistry_geog: 94, average: 95.0 },
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'Model High School',
      isSameSchool: true,
    },
    parents: {
      fatherName: 'Samuel Worku',
      fatherPhone: '+251 91 333 4455',
      motherName: 'Almaz Kifle',
      motherPhone: '+251 92 444 5566',
    },
    emergencyContact: {
      name: 'Dr. Meron Samuel',
      phone1: '+251 91 555 7766',
      phone2: '+251 94 888 2211',
      relationship: 'Sister',
    },
    registrationStatus: 'COMPLETE',
    mustChangePasswordOnLogin: false,
    password: 'Password@123',
    idCardCollected: true,
    streamChangeRequest: null,
    lostIdRequest: null,
  },
  {
    id: 'OSK-2026-1202',
    accountNumber: 'ACC-12488',
    fullName: 'Dawit Abebe Girma',
    gender: 'Male',
    dob: '2008-05-30',
    grade: 12,
    stream: 'Social Sciences',
    sectionId: '12-SOC-A',
    eighthGradeCertAttached: true,
    entranceExamScore: 91,
    ninthGradeResults: { math: 80, english: 92, science: 85, average: 85.6 },
    tenthGradeResults: { math: 84, english: 94, science: 86, average: 88.0 },
    eleventhGradeResults: { math: 86, physics_history: 96, chemistry_geog: 95, average: 92.3 },
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'Model High School',
      isSameSchool: true,
    },
    parents: {
      fatherName: 'Abebe Girma',
      fatherPhone: '+251 91 777 8899',
      motherName: 'Tsehay Welde',
      motherPhone: '+251 92 111 3322',
    },
    emergencyContact: {
      name: 'Mekonnen Girma',
      phone1: '+251 91 666 2211',
      phone2: '+251 93 888 9900',
      relationship: 'Uncle',
    },
    registrationStatus: 'COMPLETE',
    mustChangePasswordOnLogin: false,
    password: 'Password@123',
    idCardCollected: true,
    streamChangeRequest: null,
    lostIdRequest: null,
  },
  {
    id: 'OSK-2026-0903',
    accountNumber: 'ACC-90428',
    fullName: 'Bethelhem Daniel Asfaw',
    gender: 'Female',
    dob: '2011-09-14',
    grade: 9,
    stream: null,
    sectionId: null, // Pending section allocation
    eighthGradeCertAttached: true,
    entranceExamScore: 91,
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'St. Joseph Preparatory',
      isSameSchool: false,
    },
    parents: {
      fatherName: 'Daniel Asfaw',
      fatherPhone: '+251 91 333 7788',
      motherName: 'Almaz Tadesse',
      motherPhone: '+251 92 444 8899',
      email: 'daniel.asfaw@gmail.com',
    },
    emergencyContact: {
      name: 'Kassa Asfaw (Uncle)',
      phone1: '+251 91 111 2233',
      phone2: '+251 94 333 4455',
      relationship: 'Uncle',
    },
    registrationStatus: 'PENDING_PAYMENT', // Pending payment admission
    mustChangePasswordOnLogin: true,
    password: 'Password@123',
    idCardCollected: false,
    streamChangeRequest: null,
    lostIdRequest: null,
  },
  {
    id: 'OSK-2026-1003',
    accountNumber: 'ACC-10295',
    fullName: 'Kassahun Belayneh Tesfaye',
    gender: 'Male',
    dob: '2010-06-20',
    grade: 10,
    stream: null,
    sectionId: null, // Pending section allocation by Program Office
    eighthGradeCertAttached: true,
    entranceExamScore: 87,
    ninthGradeResults: { math: 84, english: 86, science: 88, average: 86 },
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    previousSchool: {
      name: 'South Addis Junior High',
      isSameSchool: false,
    },
    parents: {
      fatherName: 'Belayneh Tesfaye',
      fatherPhone: '+251 91 555 1212',
      motherName: 'Hiwot Demisse',
      motherPhone: '+251 92 666 3434',
      email: 'belayneh.tesfaye@gmail.com',
    },
    emergencyContact: {
      name: 'Solomon Tesfaye',
      phone1: '+251 91 777 9900',
      phone2: '+251 93 444 6677',
      relationship: 'Brother',
    },
    registrationStatus: 'COMPLETE',
    mustChangePasswordOnLogin: false,
    password: 'Password@123',
    idCardCollected: false,
    streamChangeRequest: null,
    lostIdRequest: null,
  }
];

export const INITIAL_SECTIONS: Section[] = [
  { id: '9A', grade: 9, sectionLetter: 'A', stream: null, homeroomTeacherId: 'TCH-01', homeroomTeacherName: 'Ato Dawit Lemma', capacity: 35 },
  { id: '9B', grade: 9, sectionLetter: 'B', stream: null, homeroomTeacherId: 'TCH-02', homeroomTeacherName: 'W/ro Selamawit Hailu', capacity: 35 },
  { id: '9C', grade: 9, sectionLetter: 'C', stream: null, homeroomTeacherId: null, homeroomTeacherName: null, capacity: 35 },
  { id: '10A', grade: 10, sectionLetter: 'A', stream: null, homeroomTeacherId: 'TCH-03', homeroomTeacherName: 'Mr. Michael Abera', capacity: 35 },
  { id: '10B', grade: 10, sectionLetter: 'B', stream: null, homeroomTeacherId: null, homeroomTeacherName: null, capacity: 35 },
  { id: '11-NAT-A', grade: 11, sectionLetter: 'A', stream: 'Natural Sciences', homeroomTeacherId: 'TCH-04', homeroomTeacherName: 'Mrs. Elena Rostova', capacity: 30 },
  { id: '11-SOC-A', grade: 11, sectionLetter: 'A', stream: 'Social Sciences', homeroomTeacherId: 'TCH-05', homeroomTeacherName: 'Ato Berhanu Negash', capacity: 30 },
  { id: '12-NAT-A', grade: 12, sectionLetter: 'A', stream: 'Natural Sciences', homeroomTeacherId: 'TCH-06', homeroomTeacherName: 'Dr. Tariku Shibeshi', capacity: 30 },
  { id: '12-SOC-A', grade: 12, sectionLetter: 'A', stream: 'Social Sciences', homeroomTeacherId: null, homeroomTeacherName: null, capacity: 30 },
];

export const INITIAL_TEACHERS: Teacher[] = [
  { id: 'TCH-01', name: 'Ato Dawit Lemma', email: 'dawit.lemma@oskaracademy.edu', subject: 'Mathematics (9 & 10)', isHomeroom: true, assignedSectionId: '9A', assignedSections: ['9A', '9B'] },
  { id: 'TCH-02', name: 'W/ro Selamawit Hailu', email: 'selamawit.h@oskaracademy.edu', subject: 'English Literature', isHomeroom: true, assignedSectionId: '9B', assignedSections: ['9A', '9B', '10A'] },
  { id: 'TCH-03', name: 'Mr. Michael Abera', email: 'michael.abera@oskaracademy.edu', subject: 'Physics & Chemistry', isHomeroom: true, assignedSectionId: '10A', assignedSections: ['10A', '10B'] },
  { id: 'TCH-04', name: 'Mrs. Elena Rostova', email: 'elena.rostova@oskaracademy.edu', subject: 'Advanced Biology & Chemistry', isHomeroom: true, assignedSectionId: '11-NAT-A', assignedSections: ['11-NAT-A', '12-NAT-A'] },
  { id: 'TCH-05', name: 'Ato Berhanu Negash', email: 'berhanu.negash@oskaracademy.edu', subject: 'Economics & History', isHomeroom: true, assignedSectionId: '11-SOC-A', assignedSections: ['11-SOC-A', '12-SOC-A'] },
  { id: 'TCH-06', name: 'Dr. Tariku Shibeshi', email: 'tariku.s@oskaracademy.edu', subject: 'Calculus & Physics', isHomeroom: true, assignedSectionId: '12-NAT-A', assignedSections: ['12-NAT-A'] },
  { id: 'TCH-07', name: 'W/t Meron Gebre', email: 'meron.g@oskaracademy.edu', subject: 'Physical Education & Health', isHomeroom: false, assignedSectionId: null, assignedSections: ['9A', '10A', '11-NAT-A'] },
  { id: 'TCH-08', name: 'Ato Solomon Fisseha', email: 'solomon.f@oskaracademy.edu', subject: 'Information Technology', isHomeroom: false, assignedSectionId: null, assignedSections: ['9B', '10B', '11-SOC-A'] },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'INV-2026-001',
    studentId: 'OSK-2026-0901',
    studentName: 'Yared Melaku Tadesse',
    grade: 9,
    accountNumber: 'ACC-90412',
    title: 'Term 1 Registration & Tuition Fee',
    amount: 18500,
    dueDate: '2026-09-30',
    paidDate: '2026-09-10',
    paymentReference: 'REF-BANK-90412-01',
    status: 'PAID',
    paidWatermark: true,
    receiptNumber: 'REC-2026-0891',
  },
  {
    id: 'INV-2026-002',
    studentId: 'OSK-2026-0902',
    studentName: 'Sara Hailemariam Mengistu',
    grade: 9,
    accountNumber: 'ACC-90415',
    title: 'Term 1 Registration & Tuition Fee',
    amount: 18500,
    dueDate: '2026-09-30',
    paidDate: '2026-09-11',
    paymentReference: 'REF-BANK-90415-01',
    status: 'PAID',
    paidWatermark: true,
    receiptNumber: 'REC-2026-0894',
  },
  {
    id: 'INV-2026-003',
    studentId: 'OSK-2026-1001',
    studentName: 'Natnael Yohannes Kebede',
    grade: 10,
    accountNumber: 'ACC-10283',
    title: 'Replacement ID Badge Processing Fee',
    amount: 500,
    dueDate: '2026-09-20',
    paymentReference: 'REF-ACC-10283-ID',
    status: 'UNPAID',
    paidWatermark: false,
    urgencyLevel: 'FINAL_OVERDUE',
    parentAlertSent: false,
  },
  {
    id: 'INV-2026-004',
    studentId: 'OSK-2026-1101',
    studentName: 'Blen Daniel Alemu',
    grade: 11,
    accountNumber: 'ACC-11904',
    title: 'Term 1 Tuition & Lab Maintenance Fee',
    amount: 21000,
    dueDate: '2026-09-25',
    paymentReference: 'REF-11904-CBE-889',
    status: 'PENDING_APPROVAL',
    slipName: 'cbe_slip_blen_21000.pdf',
    paidWatermark: false,
    urgencyLevel: 'URGENT',
    parentAlertSent: false,
  },
  {
    id: 'INV-2026-005',
    studentId: 'OSK-2026-1102',
    studentName: 'Eyob Kassahun Tefera',
    grade: 11,
    accountNumber: 'ACC-11908',
    title: 'Term 1 Tuition & Lab Maintenance Fee',
    amount: 21000,
    dueDate: '2026-09-25',
    paymentReference: 'REF-11908-AWASH-441',
    status: 'PAID',
    paidDate: '2026-09-14',
    paidWatermark: true,
    receiptNumber: 'REC-2026-0912',
  },
  {
    id: 'INV-2026-006',
    studentId: 'OSK-2026-1201',
    studentName: 'Hanna Samuel Worku',
    grade: 12,
    accountNumber: 'ACC-12480',
    title: 'Term 1 Senior Year Tuition & College Counseling Fee',
    amount: 24500,
    dueDate: '2026-09-28',
    paidDate: '2026-09-05',
    paymentReference: 'REF-12480-BOA-993',
    status: 'PAID',
    paidWatermark: true,
    receiptNumber: 'REC-2026-0771',
  },
  {
    id: 'INV-2026-007',
    studentId: 'OSK-2026-0901',
    studentName: 'Yared Melaku Tadesse',
    grade: 9,
    accountNumber: 'ACC-90412',
    title: 'Term 1 Science Lab Equipment & Field Immersion Fee',
    amount: 3500,
    dueDate: '2026-09-22',
    paymentReference: 'REF-90412-LAB-01',
    status: 'UNPAID',
    paidWatermark: false,
    urgencyLevel: 'URGENT',
    parentAlertSent: false,
  },
];

export const INITIAL_BANK_STATEMENT: BankStatementRow[] = [
  {
    id: 'BS-01',
    transactionDate: '2026-09-15',
    referenceNumber: 'REF-11904-CBE-889',
    amount: 21000,
    payerName: 'Daniel Alemu Zewde',
    bankDescription: 'CBE Mobile Transfer for ACC-11904 Blen Daniel',
    matchedStudentId: 'OSK-2026-1101',
    matchedInvoiceId: 'INV-2026-004',
    status: 'MATCHED_PENDING',
  },
  {
    id: 'BS-02',
    transactionDate: '2026-09-15',
    referenceNumber: 'REF-ACC-10283-ID',
    amount: 500,
    payerName: 'Yohannes Kebede',
    bankDescription: 'Telebirr Transfer ID Replacement ACC-10283',
    matchedStudentId: 'OSK-2026-1001',
    matchedInvoiceId: 'INV-2026-003',
    status: 'MATCHED_PENDING',
  },
  {
    id: 'BS-03',
    transactionDate: '2026-09-14',
    referenceNumber: 'REF-12488-UNKNOWN',
    amount: 24500,
    payerName: 'Abebe Girma',
    bankDescription: 'Direct Deposit for Dawit Abebe ACC-12488',
    status: 'UNMATCHED',
  },
];

export const INITIAL_NOTICES: SchoolNotice[] = [
  {
    id: 'NOT-01',
    title: 'Official Commencement of Academic Year 2026/27',
    category: 'Academic Calendar',
    content: 'Welcome students and esteemed parents. Formal class instruction is now underway. Please ensure all student ID badges and portal registrations are finalized with the Registrar.',
    postedBy: 'Dr. Henok Kebede',
    postedRole: 'School Principal',
    date: '2026-09-01',
    targetAudience: 'ALL',
    isUrgent: false,
  },
  {
    id: 'NOT-02',
    title: 'Grade 11 Stream Selection Final Deadline (15-Day Policy)',
    category: 'Academic Calendar',
    content: 'Notice to all Grade 11 students: Any requests to transfer between Natural Sciences and Social Sciences must be lodged via the student portal before September 20. Pending requests will hold classroom allocation.',
    postedBy: 'Sister Bethlehem Teklu',
    postedRole: 'Head of Admissions & Registrar',
    date: '2026-09-05',
    targetAudience: 'STUDENTS',
    isUrgent: true,
  },
  {
    id: 'NOT-03',
    title: 'Term 1 Tuition Fee Schedule & Clearance Policy',
    category: 'Payment Due',
    content: 'Finance Office reminds families that all Term 1 Tuition fees must be cleared by September 30. Mention your unique Student Account Number as bank transfer reference.',
    postedBy: 'Ato Fisseha Tamrat',
    postedRole: 'Chief Financial Officer',
    date: '2026-09-08',
    targetAudience: 'PARENTS',
    isUrgent: false,
  },
];

export const INITIAL_TEACHER_DAY_OFFS: TeacherDayOffRequest[] = [
  {
    id: 'TDO-101',
    teacherId: 'TCH-03',
    teacherName: 'Mr. Michael Abera',
    date: '2026-09-18',
    reason: 'Scheduled medical appointment at St. Paul Hospital',
    supportingDocName: 'medical_referral_appointment.pdf',
    status: 'PENDING',
    appliedDate: '2026-09-15',
    affectedSections: ['10A', '10B'],
  },
  {
    id: 'TCH-102',
    teacherId: 'TCH-05',
    teacherName: 'Ato Berhanu Negash',
    date: '2026-09-10',
    reason: 'National Curriculum Workshop Conference',
    supportingDocName: 'moe_invitation_letter.pdf',
    status: 'APPROVED',
    appliedDate: '2026-09-03',
    approvedDate: '2026-09-04',
    affectedSections: ['11-SOC-A'],
  },
];

export const INITIAL_DISCIPLINARY: DisciplinaryAction[] = [
  {
    id: 'DISC-01',
    studentId: 'OSK-2026-1001',
    studentName: 'Natnael Yohannes Kebede',
    grade: 10,
    sectionId: '10A',
    incidentDate: '2026-09-11',
    incidentType: 'Classroom Disruption & Tardiness',
    description: 'Repeated unexcused late arrival to Chemistry lab and failure to follow safety protocol.',
    actionTaken: '1-Day After-school Academic Detention & Formal Hearing Referral.',
    counsellorName: 'Sister Marta Wolde',
    homeroomTeacherNotified: true, // Automatically notified Mr. Michael Abera
    reversedByPrincipal: false,
    hearingScheduled: true,
    hearingDate: '2026-09-24',
    hearingTime: '10:30 AM',
    hearingLocation: 'Academic Disciplinary Board Room (Hall B, Rm 204)',
    hearingCommittee: ['Prof. Mengistu Haile (Principal)', 'Sister Marta Wolde (Counsellor)', 'Mr. Michael Abera (Homeroom Teacher)'],
    hearingStatus: 'SCHEDULED',
    parentNoticeSent: true,
    parentNoticeSentAt: '2026-09-18T10:30:00Z',
  },
  {
    id: 'DISC-02',
    studentId: 'OSK-2026-0901',
    studentName: 'Yared Melaku Tadesse',
    grade: 9,
    sectionId: '9A',
    incidentDate: '2026-09-16',
    incidentType: 'Academic Dishonesty & Examination Malpractice',
    description: 'Possession and usage of unauthorized mobile device during Section 9A Mid-Term Assessment.',
    actionTaken: 'Assessment Paper Voided & Formal Disciplinary Hearing Convened.',
    counsellorName: 'Sister Marta Wolde',
    homeroomTeacherNotified: true,
    reversedByPrincipal: false,
    hearingScheduled: true,
    hearingDate: '2026-09-26',
    hearingTime: '02:00 PM',
    hearingLocation: 'Office of the Principal (Executive Conference Chamber)',
    hearingCommittee: ['Prof. Mengistu Haile (Principal)', 'Sister Marta Wolde (Counsellor)', 'Ato Dawit Lemma (Homeroom Teacher)'],
    hearingStatus: 'SCHEDULED',
    parentNoticeSent: false,
  },
  {
    id: 'DISC-03',
    studentId: 'OSK-2026-1201',
    studentName: 'Hanna Samuel Worku',
    grade: 12,
    sectionId: '12-NAT-A',
    incidentDate: '2026-09-14',
    incidentType: 'Truancy & Unexcused Laboratory Absence',
    description: 'Missed Advanced Physics Practical Session without prior homeroom leave or medical documentation.',
    actionTaken: 'Official Warning Issued & Mandatory Academic Restitution Session.',
    counsellorName: 'Dr. Bethlehem Tadesse',
    homeroomTeacherNotified: true,
    reversedByPrincipal: false,
    hearingScheduled: false,
    parentNoticeSent: true,
    parentNoticeSentAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'DISC-04',
    studentId: 'OSK-2026-1102',
    studentName: 'Michael Teklu Wolde',
    grade: 11,
    sectionId: '11-SOC-A',
    incidentDate: '2026-09-17',
    incidentType: 'Uniform & Campus Dress Code Non-Compliance',
    description: 'Repeated non-regulation footwear and unauthorized non-academy hoodie during morning flag salute.',
    actionTaken: 'Uniform Compliance Contract signed with Pastoral Guidance.',
    counsellorName: 'Dr. Bethlehem Tadesse',
    homeroomTeacherNotified: true,
    reversedByPrincipal: false,
    hearingScheduled: false,
    parentNoticeSent: true,
    parentNoticeSentAt: '2026-09-17T14:20:00Z',
  },
  {
    id: 'DISC-05',
    studentId: 'OSK-2026-0902',
    studentName: 'Sara Hailemariam Mengistu',
    grade: 9,
    sectionId: '9B',
    incidentDate: '2026-09-08',
    incidentType: 'Laboratory Safety Breach',
    description: 'Mishandling chemical glassware without protective goggles during Section 9B Chemistry demo.',
    actionTaken: 'Counseling completed; incident resolved with written laboratory safety pledge.',
    counsellorName: 'Sister Marta Wolde',
    homeroomTeacherNotified: true,
    reversedByPrincipal: true,
    reversalReason: 'Satisfactory laboratory safety retraining completed and verified by Head of Science.',
    reversalDate: '2026-09-12',
    hearingScheduled: false,
    parentNoticeSent: true,
  },
  {
    id: 'DISC-06',
    studentId: 'OSK-2026-1101',
    studentName: 'Dawit Solomon Fikre',
    grade: 11,
    sectionId: '11-NAT-A',
    incidentDate: '2026-09-18',
    incidentType: 'Classroom Disruption & Tardiness',
    description: 'Excessive noise during silent study hall and argument with library monitor.',
    actionTaken: 'Library privileges suspended for 3 days and community restitution assigned.',
    counsellorName: 'Dr. Bethlehem Tadesse',
    homeroomTeacherNotified: true,
    reversedByPrincipal: false,
    hearingScheduled: false,
    parentNoticeSent: false,
  }
];

export const INITIAL_RECOMMENDATIONS: RecommendationRequest[] = [
  {
    id: 'REC-REQ-01',
    studentId: 'OSK-2026-1201',
    studentName: 'Hanna Samuel Worku',
    grade: 12,
    targetRole: 'TEACHER',
    recipientName: 'Dr. Tariku Shibeshi',
    recipientId: 'TCH-06',
    purpose: 'Application to Stanford University Engineering Undergraduate Program',
    status: 'COMPLETED',
    requestedDate: '2026-09-04',
    completedDate: '2026-09-12',
    letterContent: 'It is with highest honor and enthusiastic conviction that I recommend Hanna Samuel Worku for admission to your prestigious institution. In my 18 years of teaching advanced STEM curricula, Hanna ranks among the top 1% in analytical rigor, intellectual humility, and leadership in physics research projects.',
    stamped: true,
    pdfUploaded: true,
    pdfFileName: 'Hanna_Worku_Stanford_Recommendation_Dr_Tariku.pdf',
    hardCopyRequested: true,
  },
  {
    id: 'REC-REQ-02',
    studentId: 'OSK-2026-1202',
    studentName: 'Dawit Abebe Girma',
    grade: 12,
    targetRole: 'COUNSELLOR',
    recipientName: 'Sister Marta Wolde (Counsellor)',
    purpose: 'African Leadership Academy (ALA) Fellowship Application',
    status: 'IN_PROGRESS',
    requestedDate: '2026-09-10',
    stamped: false,
    pdfUploaded: false,
    hardCopyRequested: false,
  },
];

export const INITIAL_GRADES: GradeEntry[] = [
  {
    id: 'GRD-01',
    studentId: 'OSK-2026-0901',
    studentName: 'Yared Melaku Tadesse',
    grade: 9,
    sectionId: '9A',
    subject: 'Mathematics',
    teacherId: 'TCH-01',
    teacherName: 'Ato Dawit Lemma',
    test1Score: 23, // out of 25
    midtermScore: 32, // out of 35
    finalScore: 38, // out of 40
    totalGrade: 93,
    letterGrade: 'A',
    teacherComment: 'Exceptional problem-solving skills; active participant in geometry proofs.',
    semester: 'Semester 1',
  },
  {
    id: 'GRD-02',
    studentId: 'OSK-2026-0901',
    studentName: 'Yared Melaku Tadesse',
    grade: 9,
    sectionId: '9A',
    subject: 'English Literature',
    teacherId: 'TCH-02',
    teacherName: 'W/ro Selamawit Hailu',
    test1Score: 21,
    midtermScore: 30,
    finalScore: 36,
    totalGrade: 87,
    letterGrade: 'B+',
    teacherComment: 'Strong essay writing with deep thematic analysis.',
    semester: 'Semester 1',
  },
  {
    id: 'GRD-03',
    studentId: 'OSK-2026-1102',
    studentName: 'Eyob Kassahun Tefera',
    grade: 11,
    sectionId: '11-NAT-A',
    subject: 'Advanced Biology & Chemistry',
    teacherId: 'TCH-04',
    teacherName: 'Mrs. Elena Rostova',
    test1Score: 24,
    midtermScore: 34,
    finalScore: 39,
    totalGrade: 97,
    letterGrade: 'A+',
    teacherComment: 'Outstanding scientific inquiry and meticulous lab notebook maintenance.',
    semester: 'Semester 1',
  },
  {
    id: 'GRD-04',
    studentId: 'OSK-2026-1201',
    studentName: 'Hanna Samuel Worku',
    grade: 12,
    sectionId: '12-NAT-A',
    subject: 'Calculus & Physics',
    teacherId: 'TCH-06',
    teacherName: 'Dr. Tariku Shibeshi',
    test1Score: 25,
    midtermScore: 35,
    finalScore: 40,
    totalGrade: 100,
    letterGrade: 'A+',
    teacherComment: 'Flawless theoretical mastery and peer tutoring dedication.',
    semester: 'Semester 1',
  },
];

export const INITIAL_EVALUATIONS: StudentEvaluation[] = [
  {
    id: 'EV-01',
    studentId: 'OSK-2026-0901',
    studentName: 'Yared Melaku Tadesse',
    teacherId: 'TCH-01',
    teacherName: 'Ato Dawit Lemma',
    subject: 'Mathematics',
    date: '2026-09-14',
    conductRating: 'Excellent',
    academicEffort: 'High',
    comments: 'Consistently completes challenging enrichment exercises and mentors classmates in algebra.',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // 2026-09-19 (Today)
  { id: 'ATT-2026-0919-9A', date: '2026-09-19', sectionId: '9A', takenByTeacherId: 'TCH-01', takenByTeacherName: 'Ato Dawit Lemma', studentId: 'OSK-2026-0901', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0901', status: 'PRESENT', notes: 'Punctual' }] },
  { id: 'ATT-2026-0919-9B', date: '2026-09-19', sectionId: '9B', takenByTeacherId: 'TCH-02', takenByTeacherName: 'W/ro Selamawit Hailu', studentId: 'OSK-2026-0902', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0902', status: 'PRESENT', notes: 'Punctual' }] },
  { id: 'ATT-2026-0919-10A', date: '2026-09-19', sectionId: '10A', takenByTeacherId: 'TCH-03', takenByTeacherName: 'Mr. Michael Abera', studentId: 'OSK-2026-1001', status: 'LATE', records: [{ studentId: 'OSK-2026-1001', status: 'LATE', notes: 'Arrived 10 min late' }] },
  { id: 'ATT-2026-0919-11NAT', date: '2026-09-19', sectionId: '11-NAT-A', takenByTeacherId: 'TCH-04', takenByTeacherName: 'Mrs. Elena Rostova', studentId: 'OSK-2026-1102', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1102', status: 'PRESENT', notes: 'Active' }] },
  { id: 'ATT-2026-0919-12NAT', date: '2026-09-19', sectionId: '12-NAT-A', takenByTeacherId: 'TCH-06', takenByTeacherName: 'Dr. Tariku Shibeshi', studentId: 'OSK-2026-1201', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1201', status: 'PRESENT', notes: 'Punctual' }] },

  // 2026-09-18
  { id: 'ATT-2026-0918-9A', date: '2026-09-18', sectionId: '9A', takenByTeacherId: 'TCH-01', takenByTeacherName: 'Ato Dawit Lemma', studentId: 'OSK-2026-0901', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0901', status: 'PRESENT' }] },
  { id: 'ATT-2026-0918-9B', date: '2026-09-18', sectionId: '9B', takenByTeacherId: 'TCH-02', takenByTeacherName: 'W/ro Selamawit Hailu', studentId: 'OSK-2026-0902', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0902', status: 'PRESENT' }] },
  { id: 'ATT-2026-0918-10A', date: '2026-09-18', sectionId: '10A', takenByTeacherId: 'TCH-03', takenByTeacherName: 'Mr. Michael Abera', studentId: 'OSK-2026-1001', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1001', status: 'PRESENT' }] },
  { id: 'ATT-2026-0918-11NAT', date: '2026-09-18', sectionId: '11-NAT-A', takenByTeacherId: 'TCH-04', takenByTeacherName: 'Mrs. Elena Rostova', studentId: 'OSK-2026-1102', status: 'LATE', records: [{ studentId: 'OSK-2026-1102', status: 'LATE' }] },
  { id: 'ATT-2026-0918-12NAT', date: '2026-09-18', sectionId: '12-NAT-A', takenByTeacherId: 'TCH-06', takenByTeacherName: 'Dr. Tariku Shibeshi', studentId: 'OSK-2026-1201', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1201', status: 'PRESENT' }] },

  // 2026-09-17
  { id: 'ATT-2026-0917-9A', date: '2026-09-17', sectionId: '9A', takenByTeacherId: 'TCH-01', takenByTeacherName: 'Ato Dawit Lemma', studentId: 'OSK-2026-0901', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0901', status: 'PRESENT' }] },
  { id: 'ATT-2026-0917-9B', date: '2026-09-17', sectionId: '9B', takenByTeacherId: 'TCH-02', takenByTeacherName: 'W/ro Selamawit Hailu', studentId: 'OSK-2026-0902', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0902', status: 'PRESENT' }] },
  { id: 'ATT-2026-0917-10A', date: '2026-09-17', sectionId: '10A', takenByTeacherId: 'TCH-03', takenByTeacherName: 'Mr. Michael Abera', studentId: 'OSK-2026-1001', status: 'ABSENT', records: [{ studentId: 'OSK-2026-1001', status: 'ABSENT', notes: 'Unexcused' }] },
  { id: 'ATT-2026-0917-11SOC', date: '2026-09-17', sectionId: '11-SOC-A', takenByTeacherId: 'TCH-05', takenByTeacherName: 'Ato Berhanu Negash', studentId: 'OSK-2026-1102', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1102', status: 'PRESENT' }] },
  { id: 'ATT-2026-0917-12NAT', date: '2026-09-17', sectionId: '12-NAT-A', takenByTeacherId: 'TCH-06', takenByTeacherName: 'Dr. Tariku Shibeshi', studentId: 'OSK-2026-1201', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1201', status: 'PRESENT' }] },

  // 2026-09-16
  { id: 'ATT-2026-0916-9A', date: '2026-09-16', sectionId: '9A', takenByTeacherId: 'TCH-01', takenByTeacherName: 'Ato Dawit Lemma', studentId: 'OSK-2026-0901', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0901', status: 'PRESENT' }] },
  { id: 'ATT-2026-0916-9B', date: '2026-09-16', sectionId: '9B', takenByTeacherId: 'TCH-02', takenByTeacherName: 'W/ro Selamawit Hailu', studentId: 'OSK-2026-0902', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0902', status: 'PRESENT' }] },
  { id: 'ATT-2026-0916-10A', date: '2026-09-16', sectionId: '10A', takenByTeacherId: 'TCH-03', takenByTeacherName: 'Mr. Michael Abera', studentId: 'OSK-2026-1001', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1001', status: 'PRESENT' }] },
  { id: 'ATT-2026-0916-11NAT', date: '2026-09-16', sectionId: '11-NAT-A', takenByTeacherId: 'TCH-04', takenByTeacherName: 'Mrs. Elena Rostova', studentId: 'OSK-2026-1102', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1102', status: 'PRESENT' }] },
  { id: 'ATT-2026-0916-12NAT', date: '2026-09-16', sectionId: '12-NAT-A', takenByTeacherId: 'TCH-06', takenByTeacherName: 'Dr. Tariku Shibeshi', studentId: 'OSK-2026-1201', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1201', status: 'PRESENT' }] },

  // 2026-09-15
  { id: 'ATT-2026-0915-9A', date: '2026-09-15', sectionId: '9A', takenByTeacherId: 'TCH-01', takenByTeacherName: 'Ato Dawit Lemma', studentId: 'OSK-2026-0901', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0901', status: 'PRESENT', notes: 'Punctual' }] },
  { id: 'ATT-2026-0915-9B', date: '2026-09-15', sectionId: '9B', takenByTeacherId: 'TCH-02', takenByTeacherName: 'W/ro Selamawit Hailu', studentId: 'OSK-2026-0902', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0902', status: 'PRESENT' }] },
  { id: 'ATT-2026-0915-10A', date: '2026-09-15', sectionId: '10A', takenByTeacherId: 'TCH-03', takenByTeacherName: 'Mr. Michael Abera', studentId: 'OSK-2026-1001', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1001', status: 'PRESENT' }] },
  { id: 'ATT-2026-0915-11NAT', date: '2026-09-15', sectionId: '11-NAT-A', takenByTeacherId: 'TCH-04', takenByTeacherName: 'Mrs. Elena Rostova', studentId: 'OSK-2026-1102', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1102', status: 'PRESENT' }] },
  { id: 'ATT-2026-0915-12NAT', date: '2026-09-15', sectionId: '12-NAT-A', takenByTeacherId: 'TCH-06', takenByTeacherName: 'Dr. Tariku Shibeshi', studentId: 'OSK-2026-1201', status: 'EXCUSED', records: [{ studentId: 'OSK-2026-1201', status: 'EXCUSED', notes: 'Medical leave' }] },

  // 2026-09-14
  { id: 'ATT-2026-0914-9A', date: '2026-09-14', sectionId: '9A', takenByTeacherId: 'TCH-01', takenByTeacherName: 'Ato Dawit Lemma', studentId: 'OSK-2026-0901', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0901', status: 'PRESENT' }] },
  { id: 'ATT-2026-0914-9B', date: '2026-09-14', sectionId: '9B', takenByTeacherId: 'TCH-02', takenByTeacherName: 'W/ro Selamawit Hailu', studentId: 'OSK-2026-0902', status: 'LATE', records: [{ studentId: 'OSK-2026-0902', status: 'LATE', notes: 'Bus delay' }] },
  { id: 'ATT-2026-0914-10A', date: '2026-09-14', sectionId: '10A', takenByTeacherId: 'TCH-03', takenByTeacherName: 'Mr. Michael Abera', studentId: 'OSK-2026-1001', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1001', status: 'PRESENT' }] },
  { id: 'ATT-2026-0914-11NAT', date: '2026-09-14', sectionId: '11-NAT-A', takenByTeacherId: 'TCH-04', takenByTeacherName: 'Mrs. Elena Rostova', studentId: 'OSK-2026-1102', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1102', status: 'PRESENT' }] },
  { id: 'ATT-2026-0914-12NAT', date: '2026-09-14', sectionId: '12-NAT-A', takenByTeacherId: 'TCH-06', takenByTeacherName: 'Dr. Tariku Shibeshi', studentId: 'OSK-2026-1201', status: 'ABSENT', records: [{ studentId: 'OSK-2026-1201', status: 'ABSENT' }] },

  // 2026-09-11
  { id: 'ATT-2026-0911-9A', date: '2026-09-11', sectionId: '9A', takenByTeacherId: 'TCH-01', takenByTeacherName: 'Ato Dawit Lemma', studentId: 'OSK-2026-0901', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0901', status: 'PRESENT' }] },
  { id: 'ATT-2026-0911-9B', date: '2026-09-11', sectionId: '9B', takenByTeacherId: 'TCH-02', takenByTeacherName: 'W/ro Selamawit Hailu', studentId: 'OSK-2026-0902', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0902', status: 'PRESENT' }] },
  { id: 'ATT-2026-0911-10A', date: '2026-09-11', sectionId: '10A', takenByTeacherId: 'TCH-03', takenByTeacherName: 'Mr. Michael Abera', studentId: 'OSK-2026-1001', status: 'LATE', records: [{ studentId: 'OSK-2026-1001', status: 'LATE' }] },
  { id: 'ATT-2026-0911-11NAT', date: '2026-09-11', sectionId: '11-NAT-A', takenByTeacherId: 'TCH-04', takenByTeacherName: 'Mrs. Elena Rostova', studentId: 'OSK-2026-1102', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1102', status: 'PRESENT' }] },
  { id: 'ATT-2026-0911-12NAT', date: '2026-09-11', sectionId: '12-NAT-A', takenByTeacherId: 'TCH-06', takenByTeacherName: 'Dr. Tariku Shibeshi', studentId: 'OSK-2026-1201', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1201', status: 'PRESENT' }] },

  // 2026-09-10
  { id: 'ATT-2026-0910-9A', date: '2026-09-10', sectionId: '9A', takenByTeacherId: 'TCH-01', takenByTeacherName: 'Ato Dawit Lemma', studentId: 'OSK-2026-0901', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0901', status: 'PRESENT' }] },
  { id: 'ATT-2026-0910-9B', date: '2026-09-10', sectionId: '9B', takenByTeacherId: 'TCH-02', takenByTeacherName: 'W/ro Selamawit Hailu', studentId: 'OSK-2026-0902', status: 'PRESENT', records: [{ studentId: 'OSK-2026-0902', status: 'PRESENT' }] },
  { id: 'ATT-2026-0910-10A', date: '2026-09-10', sectionId: '10A', takenByTeacherId: 'TCH-03', takenByTeacherName: 'Mr. Michael Abera', studentId: 'OSK-2026-1001', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1001', status: 'PRESENT' }] },
  { id: 'ATT-2026-0910-11NAT', date: '2026-09-10', sectionId: '11-NAT-A', takenByTeacherId: 'TCH-04', takenByTeacherName: 'Mrs. Elena Rostova', studentId: 'OSK-2026-1102', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1102', status: 'PRESENT' }] },
  { id: 'ATT-2026-0910-12NAT', date: '2026-09-10', sectionId: '12-NAT-A', takenByTeacherId: 'TCH-06', takenByTeacherName: 'Dr. Tariku Shibeshi', studentId: 'OSK-2026-1201', status: 'PRESENT', records: [{ studentId: 'OSK-2026-1201', status: 'PRESENT' }] },
];

export const INITIAL_USERS: InstitutionalUser[] = [];
